// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmjEy5XTZvGFwROTNhfhJJY8UF69UPoM',
    appId: '1:906835870378:web:6f2000e9e524f43bba46d3',
    messagingSenderId: '906835870378',
    projectId: 'demochatcaa',
    authDomain: 'demochatcaa.firebaseapp.com',
    storageBucket: 'demochatcaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8goWmp3WMWGQK7ZxUgb3PBHiGflpbyHU',
    appId: '1:906835870378:android:f7ba9d8f2895633cba46d3',
    messagingSenderId: '906835870378',
    projectId: 'demochatcaa',
    storageBucket: 'demochatcaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw6rl9OoXoojkO6PQVt_rN9_d9Dnef2Xc',
    appId: '1:906835870378:ios:81984ff0666235acba46d3',
    messagingSenderId: '906835870378',
    projectId: 'demochatcaa',
    storageBucket: 'demochatcaa.appspot.com',
    iosBundleId: 'com.example.caaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw6rl9OoXoojkO6PQVt_rN9_d9Dnef2Xc',
    appId: '1:906835870378:ios:81984ff0666235acba46d3',
    messagingSenderId: '906835870378',
    projectId: 'demochatcaa',
    storageBucket: 'demochatcaa.appspot.com',
    iosBundleId: 'com.example.caaTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVmjEy5XTZvGFwROTNhfhJJY8UF69UPoM',
    appId: '1:906835870378:web:e6890a563776b64fba46d3',
    messagingSenderId: '906835870378',
    projectId: 'demochatcaa',
    authDomain: 'demochatcaa.firebaseapp.com',
    storageBucket: 'demochatcaa.appspot.com',
  );
}
